# Generated by Django 5.2.17 on 2026-08-18 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("ps4", "PlayStation 4"),
                            ("ps5", "PlayStation 5"),
                            ("pc", "PC"),
                            ("xbox", "Xbox"),
                            ("switch", "Nintendo Switch"),
                            ("other", "Other"),
                        ],
                        default="ps4",
                        max_length=20,
                    ),
                ),
                (
                    "steam_app_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "psn_id",
                    models.CharField(
                        blank=True,
                        help_text="PlayStation Store product ID if known",
                        max_length=100,
                    ),
                ),
                ("cover_url", models.URLField(blank=True)),
                (
                    "release_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("website", models.URLField(blank=True)),
                (
                    "store_type",
                    models.CharField(
                        choices=[
                            ("official", "Official Platform"),
                            ("aggregator", "Price Aggregator"),
                            ("authorized", "Authorized Reseller"),
                            ("physical", "Physical / High-street"),
                            ("keyshop", "Keyshop / Grey market"),
                            ("marketplace", "Open Marketplace"),
                        ],
                        default="official",
                        max_length=20,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="GB", help_text="ISO country code", max_length=2
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PriceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="GBP", max_length=3)),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "is_physical",
                    models.BooleanField(
                        default=False, help_text="True for disc / physical copy"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="True for second-hand (e.g. CeX)"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True, help_text="e.g. Grade A, Renewed", max_length=50
                    ),
                ),
                ("in_stock", models.BooleanField(default=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="games.game",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="games.store",
                    ),
                ),
            ],
            options={
                "ordering": ["price", "-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["game", "store", "-recorded_at"],
                        name="games_price_game_id_b993a7_idx",
                    )
                ],
            },
        ),
    ]
