# Generated by Django 5.2.17 on 2026-08-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrowseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=64)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("search", "Search"),
                            ("view", "View title"),
                            ("track", "Track price"),
                        ],
                        max_length=10,
                    ),
                ),
                ("query", models.CharField(blank=True, max_length=255)),
                ("steam_app_id", models.PositiveIntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("detail_url", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="pricerecord",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Retail / list price (Steam initial) — base for discount graphs",
                max_digits=10,
                null=True,
            ),
        ),
    ]
