# Generated by Django 5.2.17 on 2026-08-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_browsehistory_alter_pricerecord_original_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.CharField(blank=True, default="admin", max_length=120),
                ),
                ("action", models.CharField(max_length=120)),
                ("details", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(default="Game Price Tracker", max_length=120),
                ),
                (
                    "wallpaper",
                    models.CharField(
                        choices=[
                            ("comet", "Comet rain (light)"),
                            ("gradient", "Soft red gradient"),
                            ("none", "Solid dark"),
                        ],
                        default="comet",
                        max_length=20,
                    ),
                ),
                ("show_launch_prices", models.BooleanField(default=True)),
                (
                    "footer_text",
                    models.CharField(
                        blank=True,
                        default="Public Steam data · Launch prices are approximate public references",
                        max_length=255,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.AddField(
            model_name="game",
            name="admin_notes",
            field=models.TextField(
                blank=True, help_text="Editable product notes (admin)"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="launch_currency",
            field=models.CharField(blank=True, default="GBP", max_length=3),
        ),
        migrations.AddField(
            model_name="game",
            name="launch_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Approximate public launch/MSRP price for this platform/edition",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="launch_price_source",
            field=models.CharField(
                blank=True,
                help_text="Where this launch price came from (admin note)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="psn_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="pricerecord",
            name="condition",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="pricerecord",
            name="is_physical",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pricerecord",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pricerecord",
            name="original_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="country",
            field=models.CharField(default="GB", max_length=2),
        ),
    ]
